theme: jekyll-theme-minimal

# Setup
title:        Junvie Pailden's Github Page
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Junvie Pailden
  url:        http://www.siue.edu/~jpailde/ 

